# Copyright (c) 2024-2025 IQM Quantum Computers
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the
# limitations in the disclaimer below) provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the following
#   disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
#   disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of IQM Quantum Computers nor the names of its contributors may be used to endorse or promote
#   products derived from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY
# THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
"""The testing module for the iqm/qaoa/qubo_qaoa.py file."""

from typing import Any

from iqm.applications.maxcut import MaxCutInstance
from iqm.applications.mis import MISInstance
from iqm.applications.sk import SherringtonKirkpatrick
from iqm.qaoa.backends import EstimatorBackend, qiskit_circuit
from iqm.qaoa.qubo_qaoa import QUBOQAOA
from iqm.qaoa.transforming_functions import ham_graph_to_ham_operator
import numpy as np
import pytest
from qiskit.circuit.library import QAOAAnsatz
from qiskit.quantum_info import Statevector


@pytest.mark.parametrize(
    "num_layers, betas, gammas, initial_angles, exception",
    [
        (2.3, None, None, None, TypeError),  # num_layers has to be integer
        (-3, None, None, None, ValueError),  # num_layers has to be positive
        (2, None, None, [0, 1, 2], ValueError),  # len(initial_angles) has to be twice the num_layers
        (2, [], [], None, ValueError),  # len(betas) and len(gammas) have to be equal to num_layers
        (2, None, None, [], ValueError),  # len(initial_angles) has to be twice the num_layers
        (2, [0, 1, 2], [3, 4], None, ValueError),  # len(betas) has to equal len(gammas), which has to equal num_layers
        (2, [0, 1], None, None, ValueError),  # betas and gammas have to be both provided together
        (2, None, [3, 4], None, ValueError),  # betas and gammas have to be both provided together
        (2, [0, 1, 2], [3, 4, 5], None, ValueError),  # len(betas) and len(gammas) have to be equal to num_layers
        (3, [0, 1, 2], [3, 4, 5], [5, 4, 3, 2, 1, 0], ValueError),
        # betas and gammas shouldn't be provided together with initial_angles
    ],
)
def test_qubo_qaoa_initializer_detects_incorrect_layer_and_angle_inputs(
    num_layers: int,
    betas: list[float] | None,
    gammas: list[float] | None,
    initial_angles: list[float] | None,
    exception: type[BaseException],
    small_maxcut_instance: MaxCutInstance,
) -> None:
    """Test that the correct exception is raised if the layer and / or angle input parameters are invalid."""
    with pytest.raises(exception):
        QUBOQAOA(
            small_maxcut_instance, num_layers=num_layers, betas=betas, gammas=gammas, initial_angles=initial_angles
        )


def test_qaoa_circuit_mis(small_mis_instance: MISInstance) -> None:
    """Testing if the MIS QAOA circuit generated by our approach and Qiskit is equivalent.

    Compares that the circuit built by our algorithm and the one built by the ``QAOAAnsatz`` function from Qiskit
    are equivalent (they give the same statevector).
    """
    p = 2
    rng = np.random.default_rng(1337)
    b = rng.uniform(0, np.pi, size=p)
    g = rng.uniform(0, np.pi, size=p)
    my_qaoa_mis = QUBOQAOA(small_mis_instance, num_layers=p, betas=b, gammas=g)
    hamiltonian_mis = ham_graph_to_ham_operator(my_qaoa_mis.hamiltonian_graph)

    angles_for_qiskit = np.concatenate((b, g))
    qiskit_qaoa_circuit = QAOAAnsatz(hamiltonian_mis, reps=2, flatten=True).reverse_bits()
    qiskit_qaoa_circuit.assign_parameters(angles_for_qiskit, inplace=True)

    assert Statevector.from_instruction(qiskit_qaoa_circuit).equiv(
        Statevector.from_instruction(qiskit_circuit(my_qaoa_mis, measurements=False))
    )


def test_qaoa_circuit_maxcut(small_maxcut_instance: MaxCutInstance) -> None:
    """Testing if the maxcut QAOA circuit generated by our approach and Qiskit is equivalent.

    Compares that the circuit built by our algorithm and the one built by the ``QAOAAnsatz`` function from Qiskit
    are equivalent (they give the same statevector).
    """
    p = 2
    rng = np.random.default_rng(1337)
    b = rng.uniform(0, np.pi, size=p)
    g = rng.uniform(0, np.pi, size=p)
    my_qaoa_maxcut = QUBOQAOA(small_maxcut_instance, num_layers=p, betas=b, gammas=g)
    hamiltonian_maxcut = ham_graph_to_ham_operator(my_qaoa_maxcut.hamiltonian_graph)

    angles_for_qiskit = np.concatenate((b, g))
    qiskit_qaoa_circuit = QAOAAnsatz(hamiltonian_maxcut, reps=2, flatten=True).reverse_bits()
    qiskit_qaoa_circuit.assign_parameters(angles_for_qiskit, inplace=True)

    assert Statevector.from_instruction(qiskit_qaoa_circuit).equiv(
        Statevector.from_instruction(qiskit_circuit(my_qaoa_maxcut, measurements=False))
    )


def test_qaoa_circuit_sk(small_sk_instance: SherringtonKirkpatrick) -> None:
    """Testing if the SK QAOA circuit generated by our approach and Qiskit is equivalent.

    Compares that the circuit built by our algorithm and the one built by the ``QAOAAnsatz`` function from Qiskit
    are equivalent (they give the same statevector).
    """
    p = 2
    rng = np.random.default_rng(1337)
    b = rng.uniform(0, np.pi, size=p)
    g = rng.uniform(0, np.pi, size=p)
    my_qaoa_sk = QUBOQAOA(small_sk_instance, num_layers=p, betas=b, gammas=g)
    hamiltonian_sk = ham_graph_to_ham_operator(my_qaoa_sk.hamiltonian_graph)

    angles_for_qiskit = np.concatenate((b, g))
    qiskit_qaoa_circuit = QAOAAnsatz(hamiltonian_sk, reps=2, flatten=True).reverse_bits()
    qiskit_qaoa_circuit.assign_parameters(angles_for_qiskit, inplace=True)

    assert Statevector.from_instruction(qiskit_qaoa_circuit).equiv(
        Statevector.from_instruction(qiskit_circuit(my_qaoa_sk, measurements=False))
    )


@pytest.mark.parametrize(
    "p, angles, new_p, new_angles, new_trained_status",
    [
        [4, [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], 3, [0.0, 1.0, 2.0, 3.0, 4.0, 5.0], False],
        [4, [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], 5, [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 0.0, 0.0], False],
        [4, [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], 4, [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], True],
    ],
)
def test_qaoa_num_layers_setter_changes_angles(
    p: int,
    angles: list[float],
    new_p: int,
    new_angles: list[float],
    new_trained_status: bool,
    small_mis_instance: MISInstance,
) -> None:
    """Testing that setting the number of QAOA layers updates angles and sets trained status."""
    my_qaoa = QUBOQAOA(small_mis_instance, num_layers=p, initial_angles=angles)
    my_qaoa._trained = True  # Making this ``True`` to test if the ``num_layers`` setter updates it
    my_qaoa.num_layers = new_p

    assert np.array_equal(my_qaoa._angles, new_angles)
    assert my_qaoa._trained is new_trained_status


@pytest.mark.parametrize(
    "to_assign, expected_error_type",
    [
        (1.2, TypeError),  # Not integer
        (True, TypeError),  # Not integer
        (-2, ValueError),  # Not positive
    ],
)
def test_qaoa_num_layers_setter_raises_correct_error(
    small_mis_instance: MISInstance, to_assign: float | int | bool, expected_error_type: type[BaseException]
) -> None:
    """Testing that setting the number of QAOA layers works properly."""
    p = 4
    ini_ang = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
    my_qaoa = QUBOQAOA(small_mis_instance, num_layers=p, initial_angles=ini_ang)

    with pytest.raises(expected_error_type):
        my_qaoa.num_layers = to_assign


@pytest.mark.parametrize(
    "kwargs, expect_error",
    [
        # Ambiguous kwarg: 'method' exists in both → error.
        (
            {"method": "COBYLA"},
            "Ambiguous keyword argument 'method'",
        ),
        # Unknown global kwarg.
        (
            {"foo": "bar"},
            "Unknown keyword argument 'foo'",
        ),
        # Unknown namespaced kwarg for estimator.
        (
            {"estimate_nonexistent": 123},
            "maps to 'nonexistent', which is not accepted by estimator.estimate()",
        ),
        # Unknown namespaced kwarg for minimize.
        (
            {"minimize_nonexistent": 123},
            "maps to 'nonexistent', which is not accepted by scipy.optimize.minimize()",
        ),
    ],
)
def test_train_kwargs_errors(
    dummy_qaoa: QUBOQAOA, dummy_estimator: EstimatorBackend, kwargs: dict[str, Any], expect_error: str
) -> None:
    """Tests that the 'routing' of `kwargs` in :meth:`~iqm.qaoa.qubo_qaoa.QUBOQAOA.train` raises correct errors.

    Specifically checks the following 4 cases:
    1. An ambiguous kwarg that could be accepted by both inner functions.
    2. A kwarg that cannot be accepted by either inner function.
    3a. A kwarg prefixed for the estimator, that cannot however be accepted by it.
    3b. A kwarg prefixed for :func:`~scipi.optimize.minimize`, that cannot however be accepted by it.
    """
    with pytest.raises(TypeError) as excinfo:
        dummy_qaoa.train(dummy_estimator, **kwargs)
    assert expect_error in str(excinfo.value)
