#!/usr/bin/env bash
#MISE description="Lint package: iqm-pulse"
set -euo pipefail

uv run ruff format --check .
uv run ruff check .
uv run mypy src --config-file pyproject.toml --cache-dir=.mypy_cache
