#!/usr/bin/env bash
#MISE description="Test package: iqm-client"
set -euo pipefail

source "$QCCSW_ROOT/mise/scripts/qccsw-test-common.sh"

# This environment variable is interfering with the tests, so we need to
# unset it before running pytest
unset IQM_TOKEN

uv_pkg_run --extras "cirq,qiskit" pytest \
    --timeout=300 \
    --timeout_method=signal \
    --cov=./src/ \
    --cov-report=term-missing:skip-covered \
    --cov-report=xml:./coverage.xml \
    --cov-report=html:./htmlcov \
    --junitxml=./test_report.xml \
    ./tests
