#!/usr/bin/env bash
#MISE description="Test package: exa-common"
set -euo pipefail

source "$QCCSW_ROOT/mise/scripts/qccsw-test-common.sh"

uv_pkg_run pytest \
    --timeout=300 \
    --timeout_method=signal \
    --cov=./src/ \
    --cov-report=term-missing:skip-covered \
    --cov-report=xml:./coverage.xml \
    --cov-report=html:./htmlcov \
    --junitxml=./test_report.xml \
    ./tests
