# Copyright 2024-2025 IQM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Utils for Pulla compiler."""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Callable, Generator, Iterable
from copy import copy
from typing import Any, TypeAlias

import numpy as np

from exa.common.control.sweep.option.start_stop_options import StartStopOptions
from exa.common.control.sweep.sweep import Sweep
from exa.common.data.parameter import Parameter, Setting
from exa.common.data.setting_node import SettingNode
from exa.common.qcm_data.chip_topology import ChipTopology
from exa.common.sweep.util import NdSweep, ParallelSweep, Sweeps
from iqm.cpc.compiler.errors import CompilationPassError
from iqm.cpc.core.config import ComponentGrouping
from iqm.pulse.gates.measure import DEFAULT_INTEGRATION_KEY, DEFAULT_TIME_TRACE_KEY
from iqm.pulse.playlist.channel import ChannelProperties, get_channel_properties
from iqm.pulse.playlist.instructions import ReadoutMetrics
from iqm.pulse.timebox import TimeBox

CircuitGenerationFunction: TypeAlias = Callable[..., TimeBox | list[TimeBox]]

CIRCUIT_SWEEP_PARAMETER: Parameter = Parameter("circuit_index", "Circuit index")
"""The parameter for implicit circuit sweeps generated by the circuit generation function. This parameter
can be swept over to define the sweep order of the list of PulseSchedules. By default the sweep is executed as
the most outermost sweep but if it is defined in experiments default sweeps or by the user it will be executed
by the respective order"""
COUNTER_INDEX = Parameter("counter_index", "Counter state index")
"""MultiQubitCounter state index."""
RAGGED_DATA_INDEX = Parameter("ragged_data_index", "Ragged data index")
"""Index for the ragged data dimensions."""
READOUT_SLOT_SWEEP_PARAMETER: Parameter = Parameter("readout_slot", "Readout slot")
"""Parameter for the readout slot index needed when there's more than one readout per component."""
REPETITIONS = Parameter("repetitions", "Averaging bin")
"""Playlist repetitions used for averaging."""
TIME_TRACE_INDEX = Parameter("time_trace_index", "Time trace index")
"""Time trace index."""


def flatten_subscribed_components(subscribed_components: list[str] | dict[str, list[str]]) -> list[str]:
    """Flattens the subscribed components into a list and/or removes any duplicate entries.

    If the counter's grouped readout is used, the `subscribed_components` is a dict which is then transformed
    into a list (value lists concatenated in the dict's key order) and any duplicate components are removed.
    If `subscribed_components` is a list, duplicates will be removed. In both cases, the duplicate removal
    is done such thats the first occurrence of the component is kept and all others removed.

    Args:
         subscribed_components: Components to be readout. Can be either a list of names or a dict of
            grouped names.

    Returns:
        A flattened list of component names with duplicates removed.

    """
    flattened_components = []
    if isinstance(subscribed_components, dict):
        all_components = [comp for group in subscribed_components.values() for comp in group]
    else:
        all_components = subscribed_components
    for component in all_components:
        if component not in flattened_components:
            flattened_components.append(component)  # we must preserve the order while removing duplicates
    return flattened_components


def split_to_hard_and_soft_sweeps(
    sweeps: list[NdSweep], settings: SettingNode
) -> tuple[list[tuple[Sweep]], list[tuple[Sweep]]]:
    """Split the hardware and software sweeps.

    Args:
        sweeps: Hardware and software sweeps merged
        settings: The settings tree.

    Returns:
        List of software sweeps
        List of hardware sweeps

    """
    hard_sweep_nodes = ["gates", "gate_definitions", "characterization", "stages"]
    hard_sweep_parameters = []
    for node in hard_sweep_nodes:
        hard_sweep_parameters.extend([s.name for s in settings[node].all_settings])  # type:ignore[union-attr]

    def is_soft_sweep(sweep_or_tuple):  # noqa: ANN001, ANN202
        if isinstance(sweep_or_tuple, tuple):
            if len(sweep_or_tuple) == 0:
                raise ValueError("One of the given sweeps is an empty tuple.")
            # Check that sweeps in tuple are consistent
            first = is_soft_sweep(sweep_or_tuple[0])
            if all(first == is_soft_sweep(sweep) for sweep in sweep_or_tuple):
                return first
            raise ValueError("It is not possible to mix software and hardware sweeps in a tuple.")
        return (
            sweep_or_tuple.parameter.name not in hard_sweep_parameters
            and sweep_or_tuple.parameter.parent_name not in hard_sweep_parameters
        )

    user_hard_sweeps = [sweep if isinstance(sweep, tuple) else (sweep,) for sweep in sweeps if not is_soft_sweep(sweep)]
    soft_sweeps = [sweep if isinstance(sweep, tuple) else (sweep,) for sweep in sweeps if is_soft_sweep(sweep)]
    return soft_sweeps, user_hard_sweeps  # type:ignore[return-value]


def get_subscribed_components(
    components: ComponentGrouping, settings: SettingNode, readout_metrics: ReadoutMetrics
) -> list[str] | dict[str, list[str]]:
    """Get subscribed components from the settings tree.

    Args:
        components: Active components.
        settings: The settings tree.
        readout_metrics: Readout metrics.

    Returns:
        The subscribed components (dict in case counter readout is being used).

    """
    actually_measured_components = readout_metrics.get_components()
    # TODO: support dict-valued settings!
    subscribed_components = {}
    if "subscribed_groups" in settings.stages.subtrees:
        for group in settings.stages.subscribed_groups.settings:
            group_components = settings.stages.subscribed_groups[group].value
            subscribed_components[group] = [c for c in group_components if c in actually_measured_components]
    if subscribed_components:
        return subscribed_components
    # if no additional subscriptions, return measured active components
    if not settings.stages.additionally_subscribed_components.value:
        active_measured_components = [c for c in components.flatten() if c in actually_measured_components]
        return active_measured_components
    # return specifically subscribed (might not be active or not contain all the active ones)
    additionally_subscribed = [
        c for c in settings.stages.additionally_subscribed_components.value if c in actually_measured_components
    ]
    return additionally_subscribed


def split_to_pulse_and_circuit_sweeps(sweeps: NdSweep, circuit_parameters: list[str]) -> tuple[NdSweep, NdSweep]:
    """Split hard sweeps into circuit (i.e. compiler stage options) and pulse sweeps.

    Args:
        sweeps: Hard sweeps.
        circuit_parameters: stage options parameter names.

    Returns:
        Circuit sweeps and pulse sweeps.

    """
    normal_sweeps = []
    circuit_sweeps = []
    for sweep in sweeps:
        tuple_of_sweeps = sweep if isinstance(sweep, tuple) else (sweep,)
        for sweep_in_tuple in tuple_of_sweeps:
            parameter = sweep_in_tuple.parameter
            if parameter.name not in circuit_parameters and parameter.parent_name not in circuit_parameters:
                normal_sweeps.append(tuple_of_sweeps)
                break
        else:
            circuit_sweeps.append(tuple_of_sweeps)
    return circuit_sweeps, normal_sweeps


def get_full_spot_dict(
    spot: tuple[tuple[Any, ...], ...],
    parameters_nested: list[list[Parameter]],
    settings: SettingNode,
) -> tuple[dict[str, Any], tuple[Any, ...]]:
    """Get full spot data dict for a sweep spot.

    Args:
        spot: The tuple containing the sweep spot data.
        parameters_nested: The sweep parameters for the spot (formatted to reflect the structure of ``spot``).
        settings: The settings tree

    Returns:
        A tuple of (spot data dict, parameter values tuple).

    """
    full_spot_dict: dict[str, Any] = {}
    param_values: list[Any] = []
    for parameters, values in zip(parameters_nested, spot):
        for parameter, value in zip(parameters, values):
            param_values.append(value)
            param_name = parameter.parent_name or parameter.name
            param_path = param_name.split(".")
            if param_path[0] == "gate_definitions":
                if not param_path[-1] == "default_implementation":
                    raise ValueError(
                        "Sweeping settings of gate_definitions other than default_implementation "
                        "is not supported currently."
                    )  # TODO: other settings that are not read-only
            key = param_path[-1]
            if len(param_path) == 1:
                # FIXME: circuit generation setting node cannot yet align name & path, so we need this hacky workaround
                param_path = ["stages", "circuit_generation", "circuit", key]
                path_in_settings = ".".join(param_path)
            else:
                path_in_settings = param_name
            dict_node = full_spot_dict
            for frag in param_path[:-1]:
                dict_node = dict_node.setdefault(frag, {})
            if parameter.parent_name:
                prev_array_value = copy(dict_node.get(key, settings[path_in_settings].value))
                if not prev_array_value:
                    raise ValueError(f"'{path_in_settings}' cannot have empty value.")
                    # otherwise linter throws for prev_array_value[tuple of indices] = value:
                    # error: Unsupported target for indexed assignment ("Any | None")  [index]

                indices = parameter.element_indices
                if indices is None:
                    raise ValueError(f"Element-wise parameter '{path_in_settings}' missing element_indices.")
                    # so that linter does not complain as element_indices: int | list[int] | None = None

                # Parameter._finalize_element_indices() ensures that indices is always a list
                # but the linter complains without the handling of indices done here
                if isinstance(prev_array_value, list):  # implies parameter.element_indices = i or [i]
                    prev_array_value[indices if isinstance(indices, int) else indices[0]] = value
                else:  # implies parameter.element_indices = [i,j,k,...]
                    prev_array_value[tuple([indices] if isinstance(indices, int) else indices)] = value
                dict_node[key] = prev_array_value
            else:
                dict_node[key] = value

    return full_spot_dict, tuple(param_values)


def get_stage_spot_dict(stage_settings: SettingNode) -> dict[str, Any]:
    """Get a stage options spot dict reflecting the structure of ``stage_settings``."""
    stage_spot_dict: dict[str, Any] = {}
    for key, node in stage_settings.children.items():
        if isinstance(node, Setting):
            stage_spot_dict[key] = node.value
        else:
            stage_spot_dict[key] = get_stage_spot_dict(node)  # type: ignore[arg-type]
    return stage_spot_dict


def update_stage_spot_dict(
    stage_spot_dict: dict[str, Any],
    spot: tuple[tuple[Any, ...], ...],
    parameters_nested: list[list[Parameter]],
    stage_parameter_names: list[str],
    settings: SettingNode,
) -> None:
    """Update stage spot dict with sweep spot values."""

    def _update_dict(param_name: str, value: Any) -> None:
        frags = param_name.split(".")
        if len(frags) == 1:
            # FIXME: circuit generation setting node cannot yet align name & path, so we need this hacky workaround
            stage_spot_dict["circuit_generation"]["circuit"][param_name] = value
            return
        node = stage_spot_dict
        for frag in frags[1:-1]:  # here the first fragment is always "stages"
            node = node[frag]
        node[frags[-1]] = value

    element_params: dict[str, list[int] | np.ndarray] = {}
    for parameters, values in zip(parameters_nested, spot):
        for parameter, value in zip(parameters, values):
            if parameter.parent_name and parameter.element_indices:
                if parameter.parent_name.split(".")[-1] in stage_parameter_names:
                    parent_setting = next(s for s in settings.stages.all_settings if s.name == parameter.parent_name)
                    if parameter.parent_name not in element_params:
                        element_params[parameter.parent_name] = copy(parent_setting.value)
                    if isinstance(parameter.element_indices, int):
                        indices: int | tuple[int, ...] = parameter.element_indices
                    else:
                        indices = (
                            parameter.element_indices[0]
                            if len(parameter.element_indices) == 1
                            else tuple(parameter.element_indices)
                        )
                    element_params[parameter.parent_name][indices] = value  # type: ignore[index]
            elif parameter.name.split(".")[-1] in stage_parameter_names:
                _update_dict(parameter.name, value)
    for parameter_name, value in element_params.items():
        _update_dict(parameter_name, value)


def validate_inputs(circuits: Any, timeboxes: Any) -> tuple[Any, bool]:
    """Validate compilation inputs."""
    if (circuits is None and timeboxes is None) or (circuits is not None and timeboxes is not None):
        raise ValueError("Exactly one of `circuits` or `timeboxes`, must be provided.")
    if timeboxes is not None:
        data = timeboxes
        timebox_input = True
    else:
        data = circuits
        timebox_input = False
    return data, timebox_input


def process_return_parameters(  # noqa: PLR0913
    return_parameters: dict[Parameter | Setting, Sweeps | None],
    readout_metrics: ReadoutMetrics,
    settings: SettingNode,
    subscribed_components: list[str] | dict[str, list[str]],
    hard_sweeps: NdSweep,
    force_ragged_data: bool,
    chip_topology: ChipTopology,
    probe_lines: Iterable[str],
) -> tuple[dict[str, list[str]], dict[str, list[str]], dict[str, list[int]]]:
    """Add correct dimensions for all return parameters.

    Copied from sweep utils.

    Args:
        return_parameters: The return parameters of the sweeps.
        readout_metrics: The readout metrics for the run.
        settings: The settings tree.
        subscribed_components: The subscribed components.
        hard_sweeps: The hardware sweeps.
        forced_ragged_data: flag to enforce ragged data
        chip_topology: The chip topology.
        probe_lines: The probe line names used in the experiment run.

    Returns:
        The readout groups and a dict containing the return parameter names for the integrated and time_trace return
            parameters and a dict mapping ragged acquisition labels to the RO trigger counts in each segment (if
            there are no ragged acquisitions, this will be empty)

    """
    readouts_per_label = readout_metrics.integration_occurrences
    time_traces_per_label = readout_metrics.timetrace_occurrences
    tr_samples_mapping = readout_metrics.timetrace_lengths
    data_parameters: dict[str, list[str]] = {}
    ragged_data_labels: list[str] = []

    if isinstance(subscribed_components, dict):  # "counter mode readout_mode"
        counter = settings.controllers.counter
        integration_data_parameters, readout_components = _add_counter_return_parameters(
            subscribed_components, counter, return_parameters, hard_sweeps, readouts_per_label, force_ragged_data
        )
    else:
        use_ssro = settings.controllers.options.averaging_bins.value > 1
        if use_ssro:
            repetitions_sweep = Sweep(
                parameter=REPETITIONS, data=list(range(settings.controllers.options.averaging_bins.value))
            )
            hard_sweeps += [(repetitions_sweep,)]

        integration_data_parameters, readout_components, ragged_data_labels = _add_channel_return_parameters(
            subscribed_components,
            return_parameters,
            hard_sweeps,
            readouts_per_label,
            force_ragged_data,
            use_ssro,
        )
    data_parameters["integration_data_parameters"] = integration_data_parameters
    flattened_readout_components = flatten_subscribed_components(readout_components)

    if time_traces_per_label:
        # probe line is considered subscribed if it is either directly subscribed or at least one of its
        # components is subscribed
        set_subs = set(flattened_readout_components)
        with_subscribed_components = [
            p for p in probe_lines if set(chip_topology.probe_line_to_components[p]).intersection(set_subs)
        ]
        directly_subscribed_probe_lines = [
            p
            for p in flatten_subscribed_components(subscribed_components)
            if p in chip_topology.probe_lines and p not in with_subscribed_components
        ]
        subscribed_probe_lines = directly_subscribed_probe_lines + with_subscribed_components
        time_trace_data_parameters, ragged_tr_labels = _add_time_trace_return_parameters(
            subscribed_probe_lines,
            return_parameters,
            hard_sweeps,
            time_traces_per_label,
            tr_samples_mapping,
            force_ragged_data,
            use_ssro,
        )
        data_parameters["time_trace_data_parameters"] = time_trace_data_parameters
        ragged_data_labels += ragged_tr_labels

    ragged_label_counts = {
        l: s
        for l, s in {**readouts_per_label, **time_traces_per_label}.items()  # noqa: E741
        if l in ragged_data_labels  # noqa: E741
    }

    return readout_components, data_parameters, ragged_label_counts


def get_default_channel_properties(
    settings: SettingNode, chip_topology: ChipTopology
) -> tuple[dict[str, ChannelProperties], dict[str, dict[str, str]]]:
    """Get the channel properties and component to channel mapping for ScheduleBuilder.

    Args:
        settings: The settings tree.
        chip_topology: The chip topology.

    Returns:
        The channel properties and the component to channel mapping.

    """
    # FIXME iqm.pulse.playlist.channel.get_channel_properties_from_station_settings looks almost the same
    drive_controllers = {}
    flux_controllers = {}
    readout_controllers = {}
    for component_name, component_node in settings.controllers.child_nodes:
        if "readout" in component_node.children and component_name in chip_topology.probe_lines:
            readout_controllers[component_name] = component_node.readout
        if "drive" in component_node.children and "awg" in component_node.drive.children:
            drive_controllers[component_name] = component_node.drive.awg
        if "flux" in component_node.children and "awg" in component_node.flux.children:
            flux_controllers[component_name] = component_node.flux.awg
    return get_channel_properties(chip_topology, drive_controllers, flux_controllers, readout_controllers)


def _get_component_key_pair(label: str) -> tuple[str, ...]:
    """."""
    chunks = label.split("__")
    if len(chunks) < 2:
        raise ValueError(f"Label {label} can't be split.")
    return tuple(chunks[:2])


def _add_channel_return_parameters(
    subscribed_components: list[str] | dict[str, list[str]],
    return_parameters: dict[Parameter | Setting, Sweeps | None],
    hard_sweeps: NdSweep,
    readouts_per_label: dict[str, list[int]],
    force_ragged_data: bool,
    use_ssro: bool,
) -> tuple[list[str], dict[str, list[str]], list[str]]:
    """Add the default return parameters from the readout channels when counter readout is not used.

    The return parameter name is ``"<component>__<key>"``, where <key> is the measurement label key (by default
    ``"readout.result"`` if not given explicitly by the user to the measure gate call).

    In case the data is cartesian (i.e. there is uniform number of RO triggers in every segment of the playlist),
    the data will assume the dimensions of the hard sweeps:
    ``(<hard sweep dim1>, <hard sweep dim2>, ..., <hard sweep dimN>, <SS repetitions>, <num of triggers in segment>)``.

    If the data is ragged (i.e. there is non-uniform number of RO triggers the segments of the playlist), the data can
    only be indexed along the RO trigger index, giving the dimensions:
    ``(<RO trigger index>, <SS repetitions>)``. The RO trigger index dim will then be enriched in the post-processing
    with the information about in which segment it happened.

    Args:
        subscribed_components: the subscribed components.
        return_parameters: dict of return parameters to which the counter results are to be added.
        hard_sweeps: hard sweeps that define the returned data dimensions.
        readouts_per_label: num of readouts per readout label.
        force_raggged_data:
        use_ssro:

    Returns:
        - The names of the return parameters added
        - The names of the components that are to be read out, in the same order as in `subscribed_components`.
        - The acquisition labels that were found to be ragged.

    """
    readout_components = []
    labels_for_subscribed_components = defaultdict(list)
    ragged_data_labels = []
    subscribed_components = list(subscribed_components)
    for label, num_slots in readouts_per_label.items():
        component, key = _get_component_key_pair(label)
        if component in subscribed_components:
            prefix = component if key == DEFAULT_INTEGRATION_KEY else label
            return_param = Parameter(label, f"Integrated result for component={component} and measurement key={key}")
            if len(set(num_slots)) == 1 and not force_ragged_data:
                return_parameters[return_param] = hard_sweeps.copy()  # type: ignore[assignment]
                _add_readout_slots_dimension_virtual_sweep(prefix, label, num_slots[0], return_parameters, 0)
            else:  # ragged data set
                return_parameters[return_param] = _get_ragged_hard_sweeps(hard_sweeps, prefix, num_slots, use_ssro)  # type: ignore[assignment]
                ragged_data_labels.append(label)
            readout_components.append(component)
            labels_for_subscribed_components[component].append(label)
    readout_components.sort(key=subscribed_components.index)
    subscribed_labels: list[str] = []
    for component in subscribed_components:  # sort the labels in the same order as subscribed components
        labels_for_subscribed_components[component].sort()
        subscribed_labels.extend(labels_for_subscribed_components[component])
    return subscribed_labels, {"all_components": readout_components}, ragged_data_labels


def _add_counter_return_parameters(
    subscribed_components: list[str] | dict[str, list[str]],
    counter: SettingNode,
    return_parameters: dict[Parameter | Setting, Sweeps | None],
    hard_sweeps: NdSweep,
    readouts_per_label: dict[str, list[int]],
    force_ragged_data: bool,
) -> tuple[list[str], dict[str, list[str]]]:
    """Add counter results and their dimensions to return parameters when counter readout is used.

    The counter results are found under the parameter name ``counter.result``. This contains all the counter groups
    defined by ``subscribed_components`` and the measurements found in the schedule (only groups which have at least
    one subscribed component are retained). There will be one such group per each group defined in
    ``subscribed_components`` and measurement label that has a readout for at least one component in that group. The
    group names will then become ``<name in subscribed_components>__<key>`` where <key> is the measurement label key.
    However, if the default measurement key is used, the group name will be just ``<name in subscribed_components>``.

    NOTE: ragged data (non-uniform number or RO triggers along the segments) is not currently supported for the counter
    readout.

    Args:
        subscribed_components: the subscribed components.
        counter: the counter node in the settings tree.
        return_parameters: dict of return parameters to which the counter results are to be added.
        hard_sweeps: hard sweeps that define the returned data dimensions.
        readouts_per_label: num of readouts per readout label.
        force_ragged_data:

    Returns:
        The names of the return parameters added and the names of the components that are to be readout.

    """
    readouts_per_label_cartesian: dict[str, int] = {}
    for label, readouts in readouts_per_label.items():
        if len(set(readouts)) > 1 or force_ragged_data:
            raise CompilationPassError(
                "Ragged datasets (i.e. non-even number of readouts for a given readout label across segments) are not"
                f" yet supported in counter readout. Your label {label} has these readout event numbers accross the"
                f" segments: {readouts} and `force_ragged_data`"
                f" is set to `{force_ragged_data}`."
            )  # TODO: in prog RO phase3 counter readout for ragged datasets should be considered?
        readouts_per_label_cartesian[label] = readouts[0]

    def _label_groups(
        name: str, components: list[str]
    ) -> tuple[dict[str, int], dict[str, list[str]], dict[str, list[str]]]:
        labeled_group_counts: dict[str, int] = {}
        scrubbed_components: dict[str, list[str]] = {}
        labels_per_labeled_group: dict[str, list[str]] = {}
        for component in components:
            for label, num in readouts_per_label_cartesian.items():
                comp, acq_key = _get_component_key_pair(label)
                labeled_group_name = name if acq_key == DEFAULT_INTEGRATION_KEY else f"{name}__{acq_key}"
                if component == comp:
                    if labeled_group_name not in labels_per_labeled_group:
                        labels_per_labeled_group[labeled_group_name] = [label]
                    else:
                        labels_per_labeled_group[labeled_group_name].append(label)

                    if labeled_group_name not in scrubbed_components:
                        scrubbed_components[labeled_group_name] = [component]
                    elif component not in scrubbed_components[labeled_group_name]:
                        scrubbed_components[labeled_group_name].append(component)

                    if labeled_group_name not in labeled_group_counts:
                        labeled_group_counts[labeled_group_name] = num
                    elif labeled_group_counts[labeled_group_name] != num:
                        raise CompilationPassError(
                            "Within each counter group and for each readout label, there must be uniform"
                            " number of readouts."
                        )
        return labeled_group_counts, scrubbed_components, labels_per_labeled_group

    if not isinstance(subscribed_components, dict):
        groups_without_label = {"all_components": subscribed_components}
    else:
        groups_without_label = subscribed_components

    readout_components: dict[str, list[str]] = {}
    readouts_per_labeled_group: dict[str, int] = {}
    labels_per_group: dict[str, list[str]] = {}
    for name, components in groups_without_label.items():
        labeled_counts, scrubbed_components, labels = _label_groups(name, components)
        for labeled_group_name in labeled_counts:
            readout_components[labeled_group_name] = scrubbed_components[labeled_group_name]
            labels_per_group[labeled_group_name] = labels[labeled_group_name]
        readouts_per_labeled_group = {**readouts_per_labeled_group, **labeled_counts}

    readout_channels = []
    for name in readout_components:
        channels = labels_per_group[name]
        readout_channels.append(",".join(channels[::-1]))  # invert the order to conform to usual physics notation
    counter.subscribed_channels = readout_channels

    counter_basis = Sweep(
        parameter=COUNTER_INDEX,
        data=list(range(sum(2 ** len(group) for group in readout_components.values()))),
    )
    return_parameters[counter.result.parameter] = [(counter_basis,), *hard_sweeps.copy()]
    readout_counts = list(readouts_per_labeled_group.values())
    if len(set(readout_counts)) > 1:  # TODO: allow different counts per labels in prog RO phase3
        raise CompilationPassError(
            "The counter readout does not currently support different number of readouts for different readout labels."
        )
    _add_readout_slots_dimension_virtual_sweep("counter", counter.result.name, readout_counts[0], return_parameters, 1)
    return [counter.result.name], readout_components


def _add_time_trace_return_parameters(
    subscribed_probe_lines: list[str] | dict[str, list[str]],
    return_parameters: dict[Parameter | Setting, Sweeps | None],
    hard_sweeps: NdSweep,
    time_traces_per_label: dict[str, list[int]],
    tr_samples_mapping: dict[str, int],
    force_ragged_data: bool,
    use_ssro: bool,
) -> tuple[list[str], list[str]]:
    """Add the default return parameters for time trace acquisitions.

    The return parameter name is ``"<component>__<key>"``, where <key> is the measurement label key (by default
    ``"readout.time_trace"`` if not given explicitly by the user to the measure gate call).

    For ragged data handling, see :func:`_add_channel_return_parameters`.

    Args:
        subscribed_probe_lines: the subscribed probe lines.
        return_parameters: dict of return parameters to which the counter results are to be added.
        hard_sweeps: hard sweeps that define the returned data dimensions.
        time_traces_per_label: num of time_trace readouts per readout label for each segment.
        tr_samples_mapping: time trace length in samples mapped to the label.
        force_ragged_data:
        use_ssro:

    Returns:
        The names of the return parameters added and the acquisition labels that were found to be ragged.

    """
    labels_for_probe_lines = []
    ragged_data_labels = []
    for label, num_slots in time_traces_per_label.items():
        probe, key = _get_component_key_pair(label)
        if probe in subscribed_probe_lines:
            prefix = probe if key == DEFAULT_TIME_TRACE_KEY else label
            tr_index_sweep = Sweep(
                parameter=Parameter(f"{prefix}_{TIME_TRACE_INDEX.name}", f"{prefix} {TIME_TRACE_INDEX.label}"),
                data=StartStopOptions(0, tr_samples_mapping[label] - 1, step=1).data,
            )
            return_param = Parameter(label, f"Time trace for probe={probe} and measurement key={key}")
            if len(set(num_slots)) == 1 and not force_ragged_data:
                return_parameters[return_param] = [(tr_index_sweep,), *hard_sweeps.copy()]
                _add_readout_slots_dimension_virtual_sweep(prefix, label, num_slots[0], return_parameters, 1)
            else:
                ragged_sweeps = _get_ragged_hard_sweeps(hard_sweeps, f"{prefix}_time_trace", num_slots, use_ssro)
                return_parameters[return_param] = [(tr_index_sweep,), *ragged_sweeps]
                ragged_data_labels.append(label)
            labels_for_probe_lines.append(label)
    return labels_for_probe_lines, ragged_data_labels


def _get_ragged_hard_sweeps(hard_sweeps: NdSweep, prefix: str, num_slots: list[int], use_ssro: bool) -> NdSweep:
    ragged_param = Parameter(f"{prefix}_{RAGGED_DATA_INDEX.name}", f"{prefix} {RAGGED_DATA_INDEX.label}")
    ragged_index_sweep = Sweep(parameter=ragged_param, data=list(range(sum(num_slots))))
    ragged_hard_sweeps = [(ragged_index_sweep,)]
    if use_ssro:
        ragged_hard_sweeps.append(
            hard_sweeps[-1]  # type: ignore[arg-type]
        )  # the repetitions dimension is never ragged
    return ragged_hard_sweeps  # type:ignore[return-value]


def _add_readout_slots_dimension_virtual_sweep(
    prefix: str,
    readout_name: str,
    num_slots: int,
    return_parameters: dict[Parameter | Setting, Sweeps | None],
    sweep_index: int,
) -> None:
    param_mapping = {p.name: p for p in return_parameters}
    if num_slots == 1:
        return
    slot_sweep_param = Parameter(
        f"{prefix}_{READOUT_SLOT_SWEEP_PARAMETER.name}",
        f"{prefix} {READOUT_SLOT_SWEEP_PARAMETER.label}",
    )
    slot_sweep = (Sweep(parameter=slot_sweep_param, data=list(range(num_slots))),)
    if return_parameters[param_mapping[readout_name]] is None:
        return_parameters[param_mapping[readout_name]] = []
    return_parameters[param_mapping[readout_name]].insert(sweep_index, slot_sweep)  # type: ignore


def generate_sweep_spot(tuple_of_sweeps: ParallelSweep) -> Generator:  # noqa: ANN201
    """Generate a sweep spot from a tuple of sweeps.

    Args:
        tuple_of_sweeps: tuple of sweeps.

    Returns:
        The sweep spot values.

    """
    for vals in zip(*[sweep.data for sweep in tuple_of_sweeps]):
        yield vals


def assert_data_size_safety(data_upper_limit: int, hard_sweeps: dict[str, NdSweep], soft_sweeps: NdSweep) -> None:
    """Assert that exessive data amounts are not inserted into the DB.

    Args:
        data_upper_limit: The upper limit for total returned values in the data set.
        hard_sweeps: The hard sweeps mapped to their parameter names.
        soft_sweeps: list of soft sweeps.

    Raises:
         ExaError: when the total data dimensions exceed ``data_upper_limit``.

    """

    def _get_num_of_sweep_spots(sweeps: NdSweep) -> int:
        num_of_sweep_spots = 1
        for sweep_or_tuple in sweeps:
            sweep = sweep_or_tuple[0] if isinstance(sweep_or_tuple, tuple) else sweep_or_tuple
            num_of_sweep_spots *= len(sweep.data)
        return num_of_sweep_spots

    total_sweep_dims = 0
    for sweeps in hard_sweeps.values():
        total_sweep_dims += _get_num_of_sweep_spots(sweeps) * _get_num_of_sweep_spots(soft_sweeps)

    if total_sweep_dims > data_upper_limit:
        data_size_lower_bound = round(total_sweep_dims * 8 / 1e9)  # assumes a single float value for each data point
        msg = (
            f"Your experiment run would result in a total of {total_sweep_dims} data points, which corresponds"
            f" to more than {data_size_lower_bound} GBs of data. This may strain the DB heavily and/or"
            f" cause it to crash, affecting every user. It is not guaranteed the software/hardware can handle"
            f" such large runs even besides the DB. Your return parameters and their dimensions are as"
            f" follows:\n"
        )
        if soft_sweeps:
            msg += "soft_sweeps:\n"
            for sweep_or_tuple in soft_sweeps:
                sweep = sweep_or_tuple[0] if isinstance(sweep_or_tuple, tuple) else sweep_or_tuple
                msg += f"  {sweep.parameter.name}: {len(sweep.data)}\n"
        if hard_sweeps:
            msg += "return_parameters:\n"
            for name, hard in hard_sweeps.items():
                msg += f"  {name}:\n"
                for sweep_or_tuple in hard:
                    sweep = sweep_or_tuple[0] if isinstance(sweep_or_tuple, tuple) else sweep_or_tuple
                    msg += f"    {sweep.parameter.name}: {len(sweep.data)}\n"
        msg += (
            "If you are absolutely certain you still want to proceed with this run, set"
            " ``MultiQubitOptions.data_size_safety_switch``to ``False`` and try again."
        )
        raise CompilationPassError(msg)
