name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'sdk*.txt'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'sdk*.txt'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.11'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
           uv pip install setuptools
           sudo apt-get install graphviz

      - name: Build documentation
        run: |
          bash build.sh

      - name: Install and build React project
        working-directory: ./docs
        run: |
          npm ci
          npm run build

      - name: Copy React build to public folder
        working-directory: ./docs
        run: |
          mkdir -p public
          cp -r dist/* public/
          cp src/favicon.ico public/favicon.ico

      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        # Only run this step on push to main
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          folder: docs/public
          git-config-name: 'IQM'
          git-config-email: 'support@meetiqm.com'
