name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'sdk*.txt'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'sdk*.txt'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: astral-sh/setup-uv@v8.3.2
        with:
          python-version: '3.12'
          activate-environment: "true"

      - name: Install Node.js
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: |
           sudo apt-get install graphviz

      - name: Build documentation
        run: |
          bash build.sh

      - name: Copy SDK files to React public directory
        working-directory: ./docs
        run: |
          bash copy-sdk-files.sh

      - name: Install and build React project
        working-directory: ./docs
        run: |
          npm ci
          npm run build

      - name: Copy React build to public folder
        working-directory: ./docs
        run: |
          mkdir -p public
          cp -r dist/* public/
          cp src/favicon.ico public/favicon.ico
          echo "Directory structure of public folder:"
          ls public

      - name: Upload artifact for deploy-pages action
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'docs/public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
